name: one_auth
description: "Unified authentication SDK for mobile applications, supporting multi-factor authentication and secure sessions."
version: 0.1.0
homepage: https://github.com/your-repo/one_auth

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  local_auth: ^2.3.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^8.0.0
  envied: ^0.5.4+1
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  freerasp: ^6.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.8

flutter:
  # assets:
  #   - .env
